---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# gsthermal

<!-- badges: start -->

<!-- badges: end -->

## Optimize stomatal conductance while accounting for thermal costs

The package `gsthermal` contains functions for modelling stomatal conductance. Models supported are the Unified Stomatal Optimisation (USO) model (Medlyn et al. 2011), the instantaneous ProfitMax model (Sperry et al. 2017), and a series of instantaneous models derived from the ProfitMax model (Sicangco et al.). The modified ProfitMax models provide options to (1) account for the temperature response of maximum hydraulic conductivity $k_{max}$, (2) substitute gross for net carbon gain, and (3) account for the cost of thermal damage to PSII.

## Installation

You can install the development version of gsthermal from GitHub with:

``` r
# install.packages("devtools")
devtools::install_github("CamilleSicangco/gsthermal")
```

## Contents

-   Hydraulics
    -   The function `fit_Weibull` solves for the Weibull parameters for a plant's vulnerability curve.
    -   From the Weibull parameters, `calc_Pcrit` solves for the critical leaf water potential ($\psi_{leaf}$).
    -   `Ps_to_Pcrit` generates a vector of $\psi_{leaf}$ values ranging from $\psi_{soil}$ to $\psi_{crit}$.
    -   `calc_kmax` calculates the whole-plant conductance at a given temperature.
    -   `vulnerability_curve` calculates the vulnerability curve this vector, and `trans_from_vc` calculates the associated transpiration supply function.
-   Leaf physiology
    -   The functions `calc_Tleaf`, `calc_gw`, and `calc_A` solve for leaf temperature, stomatal conductance to water vapor, and photosynthesis, respectively.
-   Atmospheric variables
    -   The function `calc_Rnet` calculates net radiation.
-   Thermal damage
    -   `F0_func` calculates the fluorescence versus temperature curve.
    -   `TJmax_updated` calculates the temperature response of $J_{max}$ according to a peaked Arrhenius function multiplied by a reduction factor accounting for the thermal cost of PSII damage.
-   Cost and gain functions
    -   `hydraulic_cost` and `thermal_cost` calculate the normalized hydraulic and thermal costs, respectively.
    -   `C_gain` calculates the normalized carbon gain from photosynthesis, without constraining $C_i$.
    -   `C_gain_alt` calculates the normalized carbon gain from photosynthesis, while constraining $C_i$ between 0 and Ca.
    -   `calc_costgain` calculates the costs and gains described above for a leaf under given environmental conditions.

## Contact
Camille Sicangco: C.Sicangco@westernsydney.edu.au
